version: '2'
services:
  app:
    image: nginx:1.10
    volumes:
      - ./app:/usr/share/nginx/html
  chromedriver:
    image: blueimp/chromedriver
    environment:
      - VNC_ENABLED=true
    ports:
      - 5900:5900
  nightwatch:
    image: blueimp/nightwatch:0.9
    depends_on:
      - chromedriver
      - app
    environment:
      - WAIT_FOR_HOSTS=app:80 chromedriver:4444
    volumes:
      - ./test:/home/node
